// /home/marcio/portfolio/src/components/skillIconMap.ts
import {
  FaReact,
  FaJsSquare,
  FaHtml5,
  FaCss3Alt,
  FaSass,
  FaNodeJs,
  FaPhp,
  FaWordpress,
  FaShopify,
  FaDiscourse,
  FaDocker,
  FaLinux,
  FaGitAlt,
  FaWindows,
  FaApple,
  FaBrain,
  FaUsers,
  FaProjectDiagram,
  FaLightbulb,
  FaComments,
  FaNetworkWired,
  FaShieldAlt,
  FaFire,
  FaGlobe,
  // Add any other icons you've mapped in skillsData.ts
} from "react-icons/fa"; // Or fa6, etc.

export const skillIconMap: { [key: string]: React.ElementType } = {
  react: FaReact,
  js: FaJsSquare,
  html5: FaHtml5,
  css3: FaCss3Alt,
  sass: FaSass,
  "node-js": FaNodeJs,
  php: FaPhp,
  wordpress: FaWordpress,
  shopify: FaShopify,
  discourse: FaDiscourse,
  docker: FaDocker,
  linux: FaLinux,
  git: FaGitAlt,
  windows: FaWindows,
  apple: FaApple,
  brain: FaBrain,
  users: FaUsers,
  "project-diagram": FaProjectDiagram,
  lightbulb: FaLightbulb,
  comments: FaComments,
  "network-wired": FaNetworkWired,
  "shield-alt": FaShieldAlt,
  fire: FaFire,
  globe: FaGlobe,
  // Ensure all string keys from skillsData.ts iconUrl are present here
};
