/**
 * Build-time script to convert public/llm.md to HTML string.
 * Uses micromark with GFM extension for markdown parsing.
 * Outputs a TypeScript module exporting the raw HTML string.
 * No post-processing - pure micromark output for maximum flexibility.
 *
 * The emitted string is deliberately written already line-broken after the
 * `=`. The HTML is a single long token that exceeds Prettier's print width, so
 * Prettier breaks the assignment itself. Emitting that exact shape here keeps
 * the generated file idempotent under `format:check`: running Prettier over the
 * output is a no-op, and `pnpm prebuild` cannot reintroduce a diff.
 */

import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";
import { micromark } from "micromark";
import { gfm } from "micromark-extension-gfm";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SOURCE = resolve(__dirname, "../public/llm.md");
const OUTPUT = resolve(__dirname, "../src/data/llmHtml.ts");

function main(): void {
  const md = readFileSync(SOURCE, "utf8");
  const html = micromark(md, { extensions: [gfm()] });

  const ts = `// AUTO-GENERATED by scripts/build-llm-html.ts — DO NOT EDIT DIRECTLY
// Source: public/llm.md

export const llmHtml =
  ${JSON.stringify(html)} as const;
`;
  writeFileSync(OUTPUT, ts);
  console.log(`Generated ${OUTPUT}`);
}

main();
